!!## MODULE: SUBROUTINE CLEARn
MODULE SUB_CLEARn
!!### PURPOSE
!! Clear a pointer (deallocate + nullify).

!!### EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp,& !!((01-A-KND_IntrinsicTypes.f90))
              KIND_Csp,KIND_Cdp,&
              KIND_I1,KIND_I2,KIND_I4,KIND_I8,&
              KIND_L1,KIND_L2,KIND_L4,&
              KIND_S

!!### EXTERNAL STANDARDS
USE ISO_varying_string                           !!((03-A-ISO_varying_string.f90))

!!### DEFAULT IMPLICIT
IMPLICIT NONE

!!### DEFAULT ACCESS
PRIVATE

!!### PROCEDURE OVERLOADING
INTERFACE CLEARn
 MODULE PROCEDURE CLEARn_P0Rsp
 MODULE PROCEDURE CLEARn_P0Rdp
 MODULE PROCEDURE CLEARn_P0Csp
 MODULE PROCEDURE CLEARn_P0Cdp
 MODULE PROCEDURE CLEARn_P0I1
 MODULE PROCEDURE CLEARn_P0I2
 MODULE PROCEDURE CLEARn_P0I4
 MODULE PROCEDURE CLEARn_P0I8
 MODULE PROCEDURE CLEARn_P0L1
 MODULE PROCEDURE CLEARn_P0L2
 MODULE PROCEDURE CLEARn_P0L4
 MODULE PROCEDURE CLEARn_P0S
 MODULE PROCEDURE CLEARn_P0VS
 MODULE PROCEDURE CLEARn_P1Rsp
 MODULE PROCEDURE CLEARn_P1Rdp
 MODULE PROCEDURE CLEARn_P1Csp
 MODULE PROCEDURE CLEARn_P1Cdp
 MODULE PROCEDURE CLEARn_P1I1
 MODULE PROCEDURE CLEARn_P1I2
 MODULE PROCEDURE CLEARn_P1I4
 MODULE PROCEDURE CLEARn_P1I8
 MODULE PROCEDURE CLEARn_P1L1
 MODULE PROCEDURE CLEARn_P1L2
 MODULE PROCEDURE CLEARn_P1L4
 MODULE PROCEDURE CLEARn_P1S
 MODULE PROCEDURE CLEARn_P1VS
 MODULE PROCEDURE CLEARn_P2Rsp
 MODULE PROCEDURE CLEARn_P2Rdp
 MODULE PROCEDURE CLEARn_P2Csp
 MODULE PROCEDURE CLEARn_P2Cdp
 MODULE PROCEDURE CLEARn_P2I1
 MODULE PROCEDURE CLEARn_P2I2
 MODULE PROCEDURE CLEARn_P2I4
 MODULE PROCEDURE CLEARn_P2I8
 MODULE PROCEDURE CLEARn_P2L1
 MODULE PROCEDURE CLEARn_P2L2
 MODULE PROCEDURE CLEARn_P2L4
 MODULE PROCEDURE CLEARn_P2S
 MODULE PROCEDURE CLEARn_P2VS
 MODULE PROCEDURE CLEARn_P3Rsp
 MODULE PROCEDURE CLEARn_P3Rdp
 MODULE PROCEDURE CLEARn_P3Csp
 MODULE PROCEDURE CLEARn_P3Cdp
 MODULE PROCEDURE CLEARn_P3I1
 MODULE PROCEDURE CLEARn_P3I2
 MODULE PROCEDURE CLEARn_P3I4
 MODULE PROCEDURE CLEARn_P3I8
 MODULE PROCEDURE CLEARn_P3L1
 MODULE PROCEDURE CLEARn_P3L2
 MODULE PROCEDURE CLEARn_P3L4
 MODULE PROCEDURE CLEARn_P3S
 MODULE PROCEDURE CLEARn_P3VS
 MODULE PROCEDURE CLEARn_P4Rsp
 MODULE PROCEDURE CLEARn_P4Rdp
 MODULE PROCEDURE CLEARn_P4Csp
 MODULE PROCEDURE CLEARn_P4Cdp
 MODULE PROCEDURE CLEARn_P4I1
 MODULE PROCEDURE CLEARn_P4I2
 MODULE PROCEDURE CLEARn_P4I4
 MODULE PROCEDURE CLEARn_P4I8
 MODULE PROCEDURE CLEARn_P4L1
 MODULE PROCEDURE CLEARn_P4L2
 MODULE PROCEDURE CLEARn_P4L4
 MODULE PROCEDURE CLEARn_P4S
 MODULE PROCEDURE CLEARn_P4VS
 MODULE PROCEDURE CLEARn_P5Rsp
 MODULE PROCEDURE CLEARn_P5Rdp
 MODULE PROCEDURE CLEARn_P5Csp
 MODULE PROCEDURE CLEARn_P5Cdp
 MODULE PROCEDURE CLEARn_P5I1
 MODULE PROCEDURE CLEARn_P5I2
 MODULE PROCEDURE CLEARn_P5I4
 MODULE PROCEDURE CLEARn_P5I8
 MODULE PROCEDURE CLEARn_P5L1
 MODULE PROCEDURE CLEARn_P5L2
 MODULE PROCEDURE CLEARn_P5L4
 MODULE PROCEDURE CLEARn_P5S
 MODULE PROCEDURE CLEARn_P5VS
END INTERFACE

!!### PUBLIC ACCESS LIST
PUBLIC :: CLEARn

!!## MODULE PROCEDURES
CONTAINS

!!### PURE SUBROUTINE: CLEARn_P0Rsp
PURE SUBROUTINE CLEARn_P0Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE

!!### PURE SUBROUTINE: CLEARn_P0Rdp
PURE SUBROUTINE CLEARn_P0Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0Csp
PURE SUBROUTINE CLEARn_P0Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0Cdp
PURE SUBROUTINE CLEARn_P0Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0I1
PURE SUBROUTINE CLEARn_P0I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0I2
PURE SUBROUTINE CLEARn_P0I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_I4
PURE SUBROUTINE CLEARn_P0I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0I8
PURE SUBROUTINE CLEARn_P0I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0L1
PURE SUBROUTINE CLEARn_P0L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0L2
PURE SUBROUTINE CLEARn_P0L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0L4
PURE SUBROUTINE CLEARn_P0L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P0L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0S
PURE SUBROUTINE CLEARn_P0S( X )
INCLUDE "04-A-SUB_CLEARn_P0S.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P0VS
PURE SUBROUTINE CLEARn_P0VS( X )
INCLUDE "04-A-SUB_CLEARn_P0VS.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE



!!### PURE SUBROUTINE: CLEARn_P1Rsp
PURE SUBROUTINE CLEARn_P1Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE

!!### PURE SUBROUTINE: CLEARn_P1Rdp
PURE SUBROUTINE CLEARn_P1Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1Csp
PURE SUBROUTINE CLEARn_P1Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1Cdp
PURE SUBROUTINE CLEARn_P1Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1I1
PURE SUBROUTINE CLEARn_P1I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1I2
PURE SUBROUTINE CLEARn_P1I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_I4
PURE SUBROUTINE CLEARn_P1I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1I8
PURE SUBROUTINE CLEARn_P1I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1L1
PURE SUBROUTINE CLEARn_P1L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1L2
PURE SUBROUTINE CLEARn_P1L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1L4
PURE SUBROUTINE CLEARn_P1L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P1L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1S
PURE SUBROUTINE CLEARn_P1S( X )
INCLUDE "04-A-SUB_CLEARn_P1S.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P1VS
PURE SUBROUTINE CLEARn_P1VS( X )
INCLUDE "04-A-SUB_CLEARn_P1VS.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE




!!### PURE SUBROUTINE: CLEARn_P2Rsp
PURE SUBROUTINE CLEARn_P2Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE

!!### PURE SUBROUTINE: CLEARn_P2Rdp
PURE SUBROUTINE CLEARn_P2Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2Csp
PURE SUBROUTINE CLEARn_P2Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2Cdp
PURE SUBROUTINE CLEARn_P2Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2I1
PURE SUBROUTINE CLEARn_P2I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2I2
PURE SUBROUTINE CLEARn_P2I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_I4
PURE SUBROUTINE CLEARn_P2I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2I8
PURE SUBROUTINE CLEARn_P2I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2L1
PURE SUBROUTINE CLEARn_P2L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2L2
PURE SUBROUTINE CLEARn_P2L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2L4
PURE SUBROUTINE CLEARn_P2L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P2L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2S
PURE SUBROUTINE CLEARn_P2S( X )
INCLUDE "04-A-SUB_CLEARn_P2S.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P2VS
PURE SUBROUTINE CLEARn_P2VS( X )
INCLUDE "04-A-SUB_CLEARn_P2VS.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE



!!### PURE SUBROUTINE: CLEARn_P3Rsp
PURE SUBROUTINE CLEARn_P3Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE

!!### PURE SUBROUTINE: CLEARn_P3Rdp
PURE SUBROUTINE CLEARn_P3Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3Csp
PURE SUBROUTINE CLEARn_P3Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3Cdp
PURE SUBROUTINE CLEARn_P3Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3I1
PURE SUBROUTINE CLEARn_P3I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3I2
PURE SUBROUTINE CLEARn_P3I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_I4
PURE SUBROUTINE CLEARn_P3I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3I8
PURE SUBROUTINE CLEARn_P3I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3L1
PURE SUBROUTINE CLEARn_P3L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3L2
PURE SUBROUTINE CLEARn_P3L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3L4
PURE SUBROUTINE CLEARn_P3L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P3L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3S
PURE SUBROUTINE CLEARn_P3S( X )
INCLUDE "04-A-SUB_CLEARn_P3S.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P3VS
PURE SUBROUTINE CLEARn_P3VS( X )
INCLUDE "04-A-SUB_CLEARn_P3VS.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE




!!### PURE SUBROUTINE: CLEARn_P4Rsp
PURE SUBROUTINE CLEARn_P4Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE

!!### PURE SUBROUTINE: CLEARn_P4Rdp
PURE SUBROUTINE CLEARn_P4Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4Csp
PURE SUBROUTINE CLEARn_P4Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4Cdp
PURE SUBROUTINE CLEARn_P4Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4I1
PURE SUBROUTINE CLEARn_P4I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4I2
PURE SUBROUTINE CLEARn_P4I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_I4
PURE SUBROUTINE CLEARn_P4I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4I8
PURE SUBROUTINE CLEARn_P4I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4L1
PURE SUBROUTINE CLEARn_P4L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4L2
PURE SUBROUTINE CLEARn_P4L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4L4
PURE SUBROUTINE CLEARn_P4L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P4L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4S
PURE SUBROUTINE CLEARn_P4S( X )
INCLUDE "04-A-SUB_CLEARn_P4S.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P4VS
PURE SUBROUTINE CLEARn_P4VS( X )
INCLUDE "04-A-SUB_CLEARn_P4VS.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE




!!### PURE SUBROUTINE: CLEARn_P5Rsp
PURE SUBROUTINE CLEARn_P5Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE

!!### PURE SUBROUTINE: CLEARn_P5Rdp
PURE SUBROUTINE CLEARn_P5Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5R.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5Csp
PURE SUBROUTINE CLEARn_P5Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5Cdp
PURE SUBROUTINE CLEARn_P5Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5C.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5I1
PURE SUBROUTINE CLEARn_P5I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5I2
PURE SUBROUTINE CLEARn_P5I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_I4
PURE SUBROUTINE CLEARn_P5I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5I8
PURE SUBROUTINE CLEARn_P5I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5I.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5L1
PURE SUBROUTINE CLEARn_P5L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5L2
PURE SUBROUTINE CLEARn_P5L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5L4
PURE SUBROUTINE CLEARn_P5L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEARn_P5L.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5S
PURE SUBROUTINE CLEARn_P5S( X )
INCLUDE "04-A-SUB_CLEARn_P5S.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE


!!### PURE SUBROUTINE: CLEARn_P5VS
PURE SUBROUTINE CLEARn_P5VS( X )
INCLUDE "04-A-SUB_CLEARn_P5VS.f90.hdr"
!!--begin--
INCLUDE "04-A-SUB_CLEARn.f90.bdy"
!!--end--
END SUBROUTINE



END MODULE
