!!# MODULE <<FUN_MEMORYn>>
MODULE FUN_MEMORYn

!!## PURPOSE
!! Determine the amount of memory (in Bytes) a pointer
!! object is using.



!!## EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp,& !!((01-A-KND_IntrinsicTypes.f90))
                             KIND_Csp,KIND_Cdp,&
                             KIND_I1,KIND_I2,KIND_I4,KIND_I8,&
                             KIND_L1,KIND_L2,KIND_L4,&
                             KIND_S



!!## STANDARDS
USE ISO_varying_string                           !!((03-A-ISO_varying_string.f90))


!!## EXTERNAL PARAMETERS
USE PAR_MEMORY                                   !!((02-A-PAR_MEMORY.f90))



!!## HISTORY
! 1.[waw] Author   = William A. Wieselquist
!         Modified = 105.2006
!         Contact  = william.wieselquist AT gmail.com



!!## DEFAULT IMPLICIT
IMPLICIT NONE



!!## DEFAULT ACCESS
PRIVATE



!!## PROCEDURE OVERLOADING
INTERFACE MEMORYn
 MODULE PROCEDURE MEMORYn_P0Rsp
 MODULE PROCEDURE MEMORYn_P0Rdp
 MODULE PROCEDURE MEMORYn_P0Csp
 MODULE PROCEDURE MEMORYn_P0Cdp
 MODULE PROCEDURE MEMORYn_P0I1
 MODULE PROCEDURE MEMORYn_P0I2
 MODULE PROCEDURE MEMORYn_P0I4
 MODULE PROCEDURE MEMORYn_P0I8
 MODULE PROCEDURE MEMORYn_P0L1
 MODULE PROCEDURE MEMORYn_P0L2
 MODULE PROCEDURE MEMORYn_P0L4
 MODULE PROCEDURE MEMORYn_P0S
 MODULE PROCEDURE MEMORYn_P0VS
 MODULE PROCEDURE MEMORYn_P1Rsp
 MODULE PROCEDURE MEMORYn_P1Rdp
 MODULE PROCEDURE MEMORYn_P1Csp
 MODULE PROCEDURE MEMORYn_P1Cdp
 MODULE PROCEDURE MEMORYn_P1I1
 MODULE PROCEDURE MEMORYn_P1I2
 MODULE PROCEDURE MEMORYn_P1I4
 MODULE PROCEDURE MEMORYn_P1I8
 MODULE PROCEDURE MEMORYn_P1L1
 MODULE PROCEDURE MEMORYn_P1L2
 MODULE PROCEDURE MEMORYn_P1L4
 MODULE PROCEDURE MEMORYn_P1S
 MODULE PROCEDURE MEMORYn_P1VS
 MODULE PROCEDURE MEMORYn_P2Rsp
 MODULE PROCEDURE MEMORYn_P2Rdp
 MODULE PROCEDURE MEMORYn_P2Csp
 MODULE PROCEDURE MEMORYn_P2Cdp
 MODULE PROCEDURE MEMORYn_P2I1
 MODULE PROCEDURE MEMORYn_P2I2
 MODULE PROCEDURE MEMORYn_P2I4
 MODULE PROCEDURE MEMORYn_P2I8
 MODULE PROCEDURE MEMORYn_P2L1
 MODULE PROCEDURE MEMORYn_P2L2
 MODULE PROCEDURE MEMORYn_P2L4
 MODULE PROCEDURE MEMORYn_P2S
 MODULE PROCEDURE MEMORYn_P2VS
 MODULE PROCEDURE MEMORYn_P3Rsp
 MODULE PROCEDURE MEMORYn_P3Rdp
 MODULE PROCEDURE MEMORYn_P3Csp
 MODULE PROCEDURE MEMORYn_P3Cdp
 MODULE PROCEDURE MEMORYn_P3I1
 MODULE PROCEDURE MEMORYn_P3I2
 MODULE PROCEDURE MEMORYn_P3I4
 MODULE PROCEDURE MEMORYn_P3I8
 MODULE PROCEDURE MEMORYn_P3L1
 MODULE PROCEDURE MEMORYn_P3L2
 MODULE PROCEDURE MEMORYn_P3L4
 MODULE PROCEDURE MEMORYn_P3S
 MODULE PROCEDURE MEMORYn_P3VS
END INTERFACE

!!## PUBLIC ACCESS LIST
PUBLIC :: MEMORYn

!!## MODULE PROCEDURES
CONTAINS



!!### PURE FUNCTION: MEMORYn_P0Rsp
PURE FUNCTION MEMORYn_P0Rsp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rsp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION

!!### PURE FUNCTION: MEMORYn_P0Rdp
PURE FUNCTION MEMORYn_P0Rdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0Csp
PURE FUNCTION MEMORYn_P0Csp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Csp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0Cdp
PURE FUNCTION MEMORYn_P0Cdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Cdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0I1
PURE FUNCTION MEMORYn_P0I1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0I2
PURE FUNCTION MEMORYn_P0I2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0I4
PURE FUNCTION MEMORYn_P0I4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0I8
PURE FUNCTION MEMORYn_P0I8( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I8
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0L1
PURE FUNCTION MEMORYn_P0L1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0L2
PURE FUNCTION MEMORYn_P0L2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0L4
PURE FUNCTION MEMORYn_P0L4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0S
PURE FUNCTION MEMORYn_P0S( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_S
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0S.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0S.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P0VS
PURE FUNCTION MEMORYn_P0VS( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_VS
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P0
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P0VS.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_P0VS.f90.bdy"
!!--end--
END FUNCTION





!!### PURE FUNCTION: MEMORYn_P1Rsp
PURE FUNCTION MEMORYn_P1Rsp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rsp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION

!!### PURE FUNCTION: MEMORYn_P1Rdp
PURE FUNCTION MEMORYn_P1Rdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1Csp
PURE FUNCTION MEMORYn_P1Csp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Csp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1Cdp
PURE FUNCTION MEMORYn_P1Cdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Cdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1I1
PURE FUNCTION MEMORYn_P1I1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1I2
PURE FUNCTION MEMORYn_P1I2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1I4
PURE FUNCTION MEMORYn_P1I4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1I8
PURE FUNCTION MEMORYn_P1I8( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I8
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1L1
PURE FUNCTION MEMORYn_P1L1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1L2
PURE FUNCTION MEMORYn_P1L2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1L4
PURE FUNCTION MEMORYn_P1L4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1S
PURE FUNCTION MEMORYn_P1S( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_S
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1S.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_PxS.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P1VS
PURE FUNCTION MEMORYn_P1VS( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_VS
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P1
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P1VS.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_PxVS.f90.bdy"
!!--end--
END FUNCTION




!!### PURE FUNCTION: MEMORYn_P2Rsp
PURE FUNCTION MEMORYn_P2Rsp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rsp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION

!!### PURE FUNCTION: MEMORYn_P2Rdp
PURE FUNCTION MEMORYn_P2Rdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2Csp
PURE FUNCTION MEMORYn_P2Csp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Csp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2Cdp
PURE FUNCTION MEMORYn_P2Cdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Cdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2I1
PURE FUNCTION MEMORYn_P2I1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2I2
PURE FUNCTION MEMORYn_P2I2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2I4
PURE FUNCTION MEMORYn_P2I4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2I8
PURE FUNCTION MEMORYn_P2I8( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I8
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2L1
PURE FUNCTION MEMORYn_P2L1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2L2
PURE FUNCTION MEMORYn_P2L2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2L4
PURE FUNCTION MEMORYn_P2L4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2S
PURE FUNCTION MEMORYn_P2S( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_S
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2S.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_PxS.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P2VS
PURE FUNCTION MEMORYn_P2VS( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_VS
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P2
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P2VS.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_PxVS.f90.bdy"
!!--end--
END FUNCTION






!!### PURE FUNCTION: MEMORYn_P3Rsp
PURE FUNCTION MEMORYn_P3Rsp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rsp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION

!!### PURE FUNCTION: MEMORYn_P3Rdp
PURE FUNCTION MEMORYn_P3Rdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Rdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3R.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3Csp
PURE FUNCTION MEMORYn_P3Csp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Csp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3Cdp
PURE FUNCTION MEMORYn_P3Cdp( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_Cdp
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3C.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3I1
PURE FUNCTION MEMORYn_P3I1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3I2
PURE FUNCTION MEMORYn_P3I2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3I4
PURE FUNCTION MEMORYn_P3I4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3I8
PURE FUNCTION MEMORYn_P3I8( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_I8
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3I.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3L1
PURE FUNCTION MEMORYn_P3L1( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L1
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3L2
PURE FUNCTION MEMORYn_P3L2( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L2
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3L4
PURE FUNCTION MEMORYn_P3L4( X ) RESULT(NUM_Bytes)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_L4
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3L.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3S
PURE FUNCTION MEMORYn_P3S( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_S
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3S.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_PxS.f90.bdy"
!!--end--
END FUNCTION


!!### PURE FUNCTION: MEMORYn_P3VS
PURE FUNCTION MEMORYn_P3VS( X ) RESULT(NUM_Bytes)
!!#### LOCAL PARAMETERS
INTEGER,PARAMETER :: BYTES_PER_ELEMENT  = BYTES_PER_ELEMENT_VS
INTEGER,PARAMETER :: BYTES_FOR_OVERHEAD = BYTES_FOR_OVERHEAD_P3
INCLUDE "04-A-FUN_MEMORYn.f90.hdr"
INCLUDE "04-A-FUN_MEMORYn_P3VS.f90.hdr"
!!--begin--
INCLUDE "04-A-FUN_MEMORYn_PxVS.f90.bdy"
!!--end--
END FUNCTION



END MODULE
