!!# MODULE: SUBROUTINE CLEAR
MODULE SUB_CLEAR

!!## PURPOSE
!! Clear a scalar or array (set to 0, .false., or " ")
!! for scalars and arrays, respectively.


!!## EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp,& !!((01-A-KND_IntrinsicTypes.f90))
              KIND_Csp,KIND_Cdp,&
              KIND_I1,KIND_I2,KIND_I4,KIND_I8,&
              KIND_L1,KIND_L2,KIND_L4,&
              KIND_S


!!## EXTERNAL STANDARDS
USE ISO_varying_string                           !!((03-A-ISO_varying_string.f90))


!!## DEFAULT IMPLICIT
IMPLICIT NONE


!!## DEFAULT ACCESS
PRIVATE


!!## PROCEDURE OVERLOADING
INTERFACE CLEAR
 MODULE PROCEDURE CLEAR_Rsp
 MODULE PROCEDURE CLEAR_Rdp
 MODULE PROCEDURE CLEAR_I1
 MODULE PROCEDURE CLEAR_I2
 MODULE PROCEDURE CLEAR_I4
 MODULE PROCEDURE CLEAR_I8
 MODULE PROCEDURE CLEAR_L1
 MODULE PROCEDURE CLEAR_L2
 MODULE PROCEDURE CLEAR_L4
 MODULE PROCEDURE CLEAR_S
 MODULE PROCEDURE CLEAR_VS
END INTERFACE


!!## PUBLIC ACCESS LIST
PUBLIC :: CLEAR


!!## MODULE PROCEDURES
CONTAINS

!!### PURE ELEMENTAL SUBROUTINE: CLEAR_Rsp
PURE ELEMENTAL SUBROUTINE CLEAR_Rsp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_R.f90.hdr"
!!--begin--
X = 0._KIND_R
!!--end--
END SUBROUTINE

!!### PURE ELEMENTAL SUBROUTINE: CLEAR_Rdp
PURE ELEMENTAL SUBROUTINE CLEAR_Rdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_R.f90.hdr"
!!--begin--
X = 0._KIND_R
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_Csp
PURE ELEMENTAL SUBROUTINE CLEAR_Csp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_C.f90.hdr"
!!--begin--
X = (0._KIND_C,0._KIND_C)
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_Cdp
PURE ELEMENTAL SUBROUTINE CLEAR_Cdp( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_C.f90.hdr"
!!--begin--
X = (0._KIND_C,0._KIND_C)
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_I1
PURE ELEMENTAL SUBROUTINE CLEAR_I1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_I.f90.hdr"
!!--begin--
X = 0
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_I2
PURE ELEMENTAL SUBROUTINE CLEAR_I2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_I.f90.hdr"
!!--begin--
X = 0
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_I4
PURE ELEMENTAL SUBROUTINE CLEAR_I4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_I.f90.hdr"
!!--begin--
X = 0
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_I8
PURE ELEMENTAL SUBROUTINE CLEAR_I8( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_I.f90.hdr"
!!--begin--
X = 0
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_L1
PURE ELEMENTAL SUBROUTINE CLEAR_L1( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_L.f90.hdr"
!!--begin--
X = .FALSE.
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_L2
PURE ELEMENTAL SUBROUTINE CLEAR_L2( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_L.f90.hdr"
!!--begin--
X = .FALSE.
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_L4
PURE ELEMENTAL SUBROUTINE CLEAR_L4( X )
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "04-A-SUB_CLEAR_L.f90.hdr"
!!--begin--
X = .FALSE.
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_S
PURE ELEMENTAL SUBROUTINE CLEAR_S( X )
INCLUDE "04-A-SUB_CLEAR_S.f90.hdr"
!!--begin--
X = REPEAT(" ",LEN(X))
!!--end--
END SUBROUTINE


!!### PURE ELEMENTAL SUBROUTINE: CLEAR_VS
PURE ELEMENTAL SUBROUTINE CLEAR_VS( X )
INCLUDE "04-A-SUB_CLEAR_VS.f90.hdr"
!!--begin--
X = ""
!!--end--
END SUBROUTINE


END MODULE
