SELECT CASE(KIND_L) 
 CASE(KIND_L1) ; Lstar0% KIND=KIND_L1 ; Lstar0%L1 = L
 CASE(KIND_L2) ; Lstar0% KIND=KIND_L2 ; Lstar0%L2 = L
 CASE(KIND_L4) ; Lstar0% KIND=KIND_L4 ; Lstar0%L4 = L
 CASE DEFAULT ; Lstar0% KIND=-1
END SELECT
