!!# FUNCTION MODULE <<FUN_xyTRANSLATE>>
MODULE FUN_xyTRANSLATE

!!## PURPOSE
!! Translate objects in $2D$.




!!## DEFAULT IMPLICIT
IMPLICIT NONE



!!## DEFAULT ACCESS
PRIVATE



!!## PROCEDURE OVERLOADING
INTERFACE xyTRANSLATE_Px
 MODULE PROCEDURE xyTRANSLATE_Px_Rsp
 MODULE PROCEDURE xyTRANSLATE_Px_Rdp
END INTERFACE

INTERFACE xyTRANSLATE_Lin2
 MODULE PROCEDURE xyTRANSLATE_Lin2_Rsp
 MODULE PROCEDURE xyTRANSLATE_Lin2_Rdp
END INTERFACE



!!## PUBLIC ACCESS LIST
PUBLIC :: xyTRANSLATE_Px
PUBLIC :: xyTRANSLATE_Px_Rsp
PUBLIC :: xyTRANSLATE_Px_Rdp

PUBLIC :: xyTRANSLATE_Lin2
PUBLIC :: xyTRANSLATE_Lin2_Rsp
PUBLIC :: xyTRANSLATE_Lin2_Rdp



!!## CONTAINED PROCEDURES
CONTAINS



!!### PURE FUNCTION <<xyTRANSLATE_Px_Rsp>>
PURE FUNCTION xyTRANSLATE_Px_Rsp( N , Px , V ) RESULT( xyPx )

!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))

INCLUDE "05-B-FUN_xyTRANSLATE_Px.f90.hdr"

!!--begin--
INCLUDE "05-B-FUN_xyTRANSLATE_Px.f90.bdy"
!!--end--
END FUNCTION



!!### PURE FUNCTION <<xyTRANSLATE_Px_Rdp>>
PURE FUNCTION xyTRANSLATE_Px_Rdp( N , Px , V ) RESULT( xyPx )

!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))

INCLUDE "05-B-FUN_xyTRANSLATE_Px.f90.hdr"

!!--begin--
INCLUDE "05-B-FUN_xyTRANSLATE_Px.f90.bdy"
!!--end--
END FUNCTION



!!### PURE FUNCTION <<xyTRANSLATE_Lin2_Rsp>>
PURE FUNCTION xyTRANSLATE_Lin2_Rsp( Lin2 , V ) RESULT( xyLin2 )

!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))

INCLUDE "05-B-FUN_xyTRANSLATE_Lin2.f90.hdr"

!!--begin--
INCLUDE "05-B-FUN_xyTRANSLATE_Lin2.f90.bdy"
!!--end--
END FUNCTION



!!### PURE FUNCTION <<xyTRANSLATE_Lin2_Rdp>>
PURE FUNCTION xyTRANSLATE_Lin2_Rdp( Lin2 , V ) RESULT( xyLin2 )

!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))

INCLUDE "05-B-FUN_xyTRANSLATE_Lin2.f90.hdr"

!!--begin--
INCLUDE "05-B-FUN_xyTRANSLATE_Lin2.f90.bdy"
!!--end--
END FUNCTION


END MODULE
