!!# DEFINED ASSIGNMENT MODULE: ASN_IntrinsicS
MODULE ASN_IntrinsicS

!!## PURPOSE
!! Define assignment between intrinsic numeric type-kinds and standard
!! string S.

!!## EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp,& !!((01-A-KND_IntrinsicTypes.f90))
              KIND_Csp,KIND_Cdp,&
              KIND_I1,KIND_I2,KIND_I4,KIND_I8,&
              KIND_L1,KIND_L2,KIND_L4,&
              KIND_S

!!## DEPENDENCIES
USE PAR_IntrinsicLengths,ONLY: LEN_Rsp,LEN_Rdp,& !!((02-A-PAR_IntrinsicLengths.f90))
                  LEN_Csp,LEN_Cdp,&
                  LEN_I1,LEN_I2,LEN_I4,LEN_I8,&
                  LEN_L1,LEN_L2,LEN_L4
USE FUN_Error                                    !!((04-A-FUN_Error.f90))


!!## DEFAULT IMPLICIT
IMPLICIT NONE


!!## DEFAULT ACCESS
PRIVATE


!!## DEFINED ASSIGNMENT
INTERFACE ASSIGNMENT(=)
 MODULE PROCEDURE Csp_EQUALS_S
 MODULE PROCEDURE Cdp_EQUALS_S
 MODULE PROCEDURE Rsp_EQUALS_S
 MODULE PROCEDURE Rdp_EQUALS_S
 MODULE PROCEDURE I1_EQUALS_S
 MODULE PROCEDURE I2_EQUALS_S
 MODULE PROCEDURE I4_EQUALS_S
 MODULE PROCEDURE I8_EQUALS_S
 MODULE PROCEDURE L1_EQUALS_S
 MODULE PROCEDURE L2_EQUALS_S
 MODULE PROCEDURE L4_EQUALS_S
 MODULE PROCEDURE S_EQUALS_Csp
 MODULE PROCEDURE S_EQUALS_Cdp
 MODULE PROCEDURE S_EQUALS_Rsp
 MODULE PROCEDURE S_EQUALS_Rdp
 MODULE PROCEDURE S_EQUALS_I1
 MODULE PROCEDURE S_EQUALS_I2
 MODULE PROCEDURE S_EQUALS_I4
 MODULE PROCEDURE S_EQUALS_I8
 MODULE PROCEDURE S_EQUALS_L1
 MODULE PROCEDURE S_EQUALS_L2
 MODULE PROCEDURE S_EQUALS_L4
END INTERFACE


!!## ACCESS
PUBLIC :: ASSIGNMENT(=)


!!## CONTAINED PROCEDURES
CONTAINS


PURE ELEMENTAL SUBROUTINE Csp_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Cout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_Cout.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE Cdp_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Cout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_Cout.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_Csp(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp    !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_Csp
INCLUDE "05-B-ASN_IntrinsicS_Cin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_Cdp(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp    !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_Cdp
INCLUDE "05-B-ASN_IntrinsicS_Cin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE Rsp_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Rout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_out.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE Rdp_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Rout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_out.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_Rsp(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp    !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_Rsp
INCLUDE "05-B-ASN_IntrinsicS_Rin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_Rdp(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp    !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_Rdp
INCLUDE "05-B-ASN_IntrinsicS_Rin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE


PURE ELEMENTAL SUBROUTINE I1_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Iout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_out.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_I1(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_I1
INCLUDE "05-B-ASN_IntrinsicS_Iin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE


PURE ELEMENTAL SUBROUTINE I2_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Iout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_out.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_I2(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_I2
INCLUDE "05-B-ASN_IntrinsicS_Iin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE


PURE ELEMENTAL SUBROUTINE I4_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Iout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_out.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_I4(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_I4
INCLUDE "05-B-ASN_IntrinsicS_Iin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE


PURE ELEMENTAL SUBROUTINE I8_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Iout.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_out.f90.bdy"
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_I8(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_I8
INCLUDE "05-B-ASN_IntrinsicS_Iin.f90.hdr"
!
INCLUDE "05-B-ASN_IntrinsicS_in.f90.bdy"
!
ENDSUBROUTINE




PURE ELEMENTAL SUBROUTINE L1_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Lout.f90.hdr"
!
READ(S,*,IOSTAT=jerr)X
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_L1(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_L1
INCLUDE "05-B-ASN_IntrinsicS_Lin.f90.hdr"
!
WRITE(S,*,IOSTAT=jerr)X
S=ADJUSTL(S)
!
ENDSUBROUTINE


PURE ELEMENTAL SUBROUTINE L2_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Lout.f90.hdr"
!
READ(S,*,IOSTAT=jerr)X
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_L2(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_L2
INCLUDE "05-B-ASN_IntrinsicS_Lin.f90.hdr"
!
WRITE(S,*,IOSTAT=jerr)X
S=ADJUSTL(S)
!
ENDSUBROUTINE


PURE ELEMENTAL SUBROUTINE L4_EQUALS_S(X,S)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-ASN_IntrinsicS_Lout.f90.hdr"
!
READ(S,*,IOSTAT=jerr)X
!
ENDSUBROUTINE

PURE ELEMENTAL SUBROUTINE S_EQUALS_L4(S,X)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4     !!((01-A-KND_IntrinsicTypes.f90))
INTEGER,PARAMETER :: LEN_S=LEN_L4
INCLUDE "05-B-ASN_IntrinsicS_Lin.f90.hdr"
!
WRITE(S,*,IOSTAT=jerr)X
S=ADJUSTL(S)
!
ENDSUBROUTINE


ENDMODULE
