MODULE FUN_xyzDETERMINANT
!!#### PURPOSE
!! Calculates the determinant of a 3x3 matrix.

!!#### EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))

!!#### DEFAULT IMPLICIT
IMPLICIT NONE

!!#### DEFAULT ACCESS
PRIVATE

!!#### PROCEDURE OVERLOADING
INTERFACE xyzDETERMINANT
 MODULE PROCEDURE xyzDETERMINANT_Rsp
 MODULE PROCEDURE xyzDETERMINANT_Rdp
END INTERFACE

!!#### PUBLIC ACCESS LIST
PUBLIC :: xyzDETERMINANT


CONTAINS


FUNCTION xyzDETERMINANT_Rsp( M33 ) RESULT(d)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp  !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-FUN_xyzDETERMINANT.f90.hdr"
!!--begin--
INCLUDE "05-B-FUN_xyzDETERMINANT.f90.bdy"
!!--end--
END FUNCTION

FUNCTION xyzDETERMINANT_Rdp( M33 ) RESULT(d)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp  !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "05-B-FUN_xyzDETERMINANT.f90.hdr"
!!--begin--
INCLUDE "05-B-FUN_xyzDETERMINANT.f90.bdy"
!!--end--
END FUNCTION

END MODULE
