INTERSECT = xyINTERSECT_LnLn( Ry_a , Ry_b , SDIST_a=DIST0_a , SDIST_b=DIST0_b )

IF( .NOT.INTERSECT )RETURN

IF( DIST0_a<=0._KIND_R )THEN
 INTERSECT = .FALSE.
 RETURN
ENDIF

IF( DIST0_b<=0._KIND_R )THEN
 INTERSECT = .FALSE.
 RETURN
ENDIF

IF( PRESENT(DIST_a) )THEN
 DIST_a = DIST0_a
ENDIF

IF( PRESENT(DIST_b) )THEN
 DIST_b = DIST0_b
ENDIF

IF( PRESENT(P_intersect) )THEN
 P_intersect = Ry_a(:,1) + DIST0_a*Ry_a(:,2)
ENDIF

 