INTERSECT = xyINTERSECT_LnLn( Ln , Ry , SDIST_a=SDIST_Ln , SDIST_b=DIST )

IF( .NOT.INTERSECT )RETURN

IF( DIST<=0._KIND_R )THEN
 INTERSECT = .FALSE.
 RETURN
ENDIF

IF( PRESENT(DIST_Ry) )THEN
 DIST_Ry = DIST
ENDIF

IF( PRESENT(P_intersect) )THEN
 P_intersect = Ry(:,1) + DIST*Ry(:,2)
ENDIF

 