!!# SUBROUTINE MODULE: <SAVEn>
MODULE SUB_SAVEn

!!## PURPOSE
!! Saves pointer array data to a file.


!!## USAGE
!
!        CALL SAVEn("P",P)
!
!! saves data pointer <P> to file "P.dat" (formatted data)
!! or "P.unf" (unformatted data).


!!## DETAILS
!! Another procedure, <LOADn> exists to load the data.
!
!     CALL LOADn("P",P)
!
!! loads data pointer <P> from "P.dat" (formatted data) or
!! "P.unf" (unformatted data).


!!## FORTRAN STANDARDS
USE ISO_varying_string                           !!((03-A-ISO_varying_string.f90))

!!## EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp,& !!((01-A-KND_IntrinsicTypes.f90))
              KIND_Csp,KIND_Cdp,&
              KIND_I1,KIND_I2,KIND_I4,KIND_I8,&
              KIND_L1,KIND_L2,KIND_L4,&
              KIND_S

!!## EXTERNAL PROCEDURES
USE FUN_NewUnit                                  !!((04-B-FUN_NewUnit.f90))
USE FUN_Default                                  !!((04-A-FUN_Default.f90))
USE FUN_STR                                      !!((05-B-FUN_STR.f90))

!!## DEFAULT IMPLICIT
IMPLICIT NONE

!!## DEFAULT ACCESS
PRIVATE

!!## PROCEDURE OVERLOADING
INTERFACE SAVEn
 MODULE PROCEDURE SAVEn_P1Rsp
 MODULE PROCEDURE SAVEn_P1Rdp
 MODULE PROCEDURE SAVEn_P1Csp
 MODULE PROCEDURE SAVEn_P1Cdp
 MODULE PROCEDURE SAVEn_P1I1
 MODULE PROCEDURE SAVEn_P1I2
 MODULE PROCEDURE SAVEn_P1I4
 MODULE PROCEDURE SAVEn_P1I8
 MODULE PROCEDURE SAVEn_P1L1
 MODULE PROCEDURE SAVEn_P1L2
 MODULE PROCEDURE SAVEn_P1L4
 MODULE PROCEDURE SAVEn_P1S
 MODULE PROCEDURE SAVEn_P1VS
 MODULE PROCEDURE SAVEn_P2Rsp
 MODULE PROCEDURE SAVEn_P2Rdp
 MODULE PROCEDURE SAVEn_P2Csp
 MODULE PROCEDURE SAVEn_P2Cdp
 MODULE PROCEDURE SAVEn_P2I1
 MODULE PROCEDURE SAVEn_P2I2
 MODULE PROCEDURE SAVEn_P2I4
 MODULE PROCEDURE SAVEn_P2I8
 MODULE PROCEDURE SAVEn_P2L1
 MODULE PROCEDURE SAVEn_P2L2
 MODULE PROCEDURE SAVEn_P2L4
 MODULE PROCEDURE SAVEn_P2S
 MODULE PROCEDURE SAVEn_P2VS
 MODULE PROCEDURE SAVEn_P3Rsp
 MODULE PROCEDURE SAVEn_P3Rdp
 MODULE PROCEDURE SAVEn_P3Csp
 MODULE PROCEDURE SAVEn_P3Cdp
 MODULE PROCEDURE SAVEn_P3I1
 MODULE PROCEDURE SAVEn_P3I2
 MODULE PROCEDURE SAVEn_P3I4
 MODULE PROCEDURE SAVEn_P3I8
 MODULE PROCEDURE SAVEn_P3L1
 MODULE PROCEDURE SAVEn_P3L2
 MODULE PROCEDURE SAVEn_P3L4
 MODULE PROCEDURE SAVEn_P3S
 MODULE PROCEDURE SAVEn_P3VS
END INTERFACE

!!## PUBLIC ACCESS LIST
PUBLIC :: SAVEn


!!## MODULE PROCEDURES
CONTAINS


!!### Rank 1 Array SAVEning Procedures
SUBROUTINE SAVEn_P1Rsp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rsp
INCLUDE "06-B-SUB_SAVEn_P1R.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1Rdp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rdp
INCLUDE "06-B-SUB_SAVEn_P1R.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVEn_P1Csp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Csp
INCLUDE "06-B-SUB_SAVEn_P1C.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1Cdp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Cdp
INCLUDE "06-B-SUB_SAVEn_P1C.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE




SUBROUTINE SAVEn_P1I1(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I1
INCLUDE "06-B-SUB_SAVEn_P1I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1I2(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I2
INCLUDE "06-B-SUB_SAVEn_P1I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1I4(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I4
INCLUDE "06-B-SUB_SAVEn_P1I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1I8(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I8
INCLUDE "06-B-SUB_SAVEn_P1I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVEn_P1L1(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L1
INCLUDE "06-B-SUB_SAVEn_P1L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1L2(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L2
INCLUDE "06-B-SUB_SAVEn_P1L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1L4(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L4
INCLUDE "06-B-SUB_SAVEn_P1L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1S(SP,P,Unformatted)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVEn_P1S.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(A)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P1VS(SP,P,Unformatted)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVEn_P1VS.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P1VS.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE




!!### Rank 2 Array SAVEning Procedures
SUBROUTINE SAVEn_P2Rsp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rsp
INCLUDE "06-B-SUB_SAVEn_P2R.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2Rdp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rdp
INCLUDE "06-B-SUB_SAVEn_P2R.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVEn_P2Csp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Csp
INCLUDE "06-B-SUB_SAVEn_P2C.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2Cdp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Cdp
INCLUDE "06-B-SUB_SAVEn_P2C.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE




SUBROUTINE SAVEn_P2I1(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I1
INCLUDE "06-B-SUB_SAVEn_P2I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2I2(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I2
INCLUDE "06-B-SUB_SAVEn_P2I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2I4(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I4
INCLUDE "06-B-SUB_SAVEn_P2I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2I8(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I8
INCLUDE "06-B-SUB_SAVEn_P2I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVEn_P2L1(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L1
INCLUDE "06-B-SUB_SAVEn_P2L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2L2(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L2
INCLUDE "06-B-SUB_SAVEn_P2L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2L4(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L4
INCLUDE "06-B-SUB_SAVEn_P2L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2S(SP,P,Unformatted)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVEn_P2S.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(A)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P2VS(SP,P,Unformatted)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVEn_P2VS.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P2VS.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE






!!### Rank 3 Array SAVEning Procedures
SUBROUTINE SAVEn_P3Rsp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rsp
INCLUDE "06-B-SUB_SAVEn_P3R.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3Rdp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rdp
INCLUDE "06-B-SUB_SAVEn_P3R.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVEn_P3Csp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Csp
INCLUDE "06-B-SUB_SAVEn_P3C.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3Cdp(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Cdp
INCLUDE "06-B-SUB_SAVEn_P3C.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(E24.17)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE




SUBROUTINE SAVEn_P3I1(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I1
INCLUDE "06-B-SUB_SAVEn_P3I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3I2(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I2
INCLUDE "06-B-SUB_SAVEn_P3I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3I4(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I4
INCLUDE "06-B-SUB_SAVEn_P3I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3I8(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I8
INCLUDE "06-B-SUB_SAVEn_P3I.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(I12)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVEn_P3L1(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L1
INCLUDE "06-B-SUB_SAVEn_P3L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3L2(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L2
INCLUDE "06-B-SUB_SAVEn_P3L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3L4(SP,P,Unformatted)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L4
INCLUDE "06-B-SUB_SAVEn_P3L.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(G4.2)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3S(SP,P,Unformatted)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVEn_P3S.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
100 FORMAT(A)
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVEn_P3VS(SP,P,Unformatted)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVEn_P3VS.f90.hdr"
INCLUDE "06-B-SUB_SAVEn.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVEn.f90.sup"
INCLUDE "06-B-SUB_SAVEn_P3VS.f90.bdy"
INCLUDE "06-B-SUB_SAVEn.f90.wup"
!!--end--
END SUBROUTINE


END MODULE
