!!## Subroutine Module: SAVE
MODULE SUB_SAVE
!!### PURPOSE
!! The subroutine saves array data to a file
!! named <filename.dat>, where each element of the array
!! appears on a line.


!!### USAGE
!
!        CALL SAVE("A",A)
!
!! loads data from "A.dat" into A.


!!### DETAILS
!! Another procedure, <LOAD> exists to LOAD the data.
!
!     CALL LOAD("A",A)
!
!! LOADs data to "A.dat".


!!### FORTRAN STANDARDS
USE ISO_varying_string                           !!((03-A-ISO_varying_string.f90))

!!### EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp,& !!((01-A-KND_IntrinsicTypes.f90))
              KIND_Csp,KIND_Cdp,&
              KIND_I1,KIND_I2,KIND_I4,KIND_I8,&
              KIND_L1,KIND_L2,KIND_L4,&
              KIND_S

!!### EXTERNAL PROCEDURES
USE FUN_NewFile                                  !!((05-B-FUN_NewFile.f90))

!!### DEFAULT IMPLICIT
IMPLICIT NONE

!!### DEFAULT ACCESS
PRIVATE

!!### PROCEDURE OVERLOADING
INTERFACE SAVE
 MODULE PROCEDURE SAVE_A1Rsp
 MODULE PROCEDURE SAVE_A1Rdp
 MODULE PROCEDURE SAVE_A1Csp
 MODULE PROCEDURE SAVE_A1Cdp
 MODULE PROCEDURE SAVE_A1I1
 MODULE PROCEDURE SAVE_A1I2
 MODULE PROCEDURE SAVE_A1I4
 MODULE PROCEDURE SAVE_A1I8
 MODULE PROCEDURE SAVE_A1L1
 MODULE PROCEDURE SAVE_A1L2
 MODULE PROCEDURE SAVE_A1L4
 MODULE PROCEDURE SAVE_A1S
 MODULE PROCEDURE SAVE_A1VS
 MODULE PROCEDURE SAVE_A2Rsp
 MODULE PROCEDURE SAVE_A2Rdp
 MODULE PROCEDURE SAVE_A2Csp
 MODULE PROCEDURE SAVE_A2Cdp
 MODULE PROCEDURE SAVE_A2I1
 MODULE PROCEDURE SAVE_A2I2
 MODULE PROCEDURE SAVE_A2I4
 MODULE PROCEDURE SAVE_A2I8
 MODULE PROCEDURE SAVE_A2L1
 MODULE PROCEDURE SAVE_A2L2
 MODULE PROCEDURE SAVE_A2L4
 MODULE PROCEDURE SAVE_A2S
 MODULE PROCEDURE SAVE_A2VS
 MODULE PROCEDURE SAVE_A3Rsp
 MODULE PROCEDURE SAVE_A3Rdp
 MODULE PROCEDURE SAVE_A3Csp
 MODULE PROCEDURE SAVE_A3Cdp
 MODULE PROCEDURE SAVE_A3I1
 MODULE PROCEDURE SAVE_A3I2
 MODULE PROCEDURE SAVE_A3I4
 MODULE PROCEDURE SAVE_A3I8
 MODULE PROCEDURE SAVE_A3L1
 MODULE PROCEDURE SAVE_A3L2
 MODULE PROCEDURE SAVE_A3L4
 MODULE PROCEDURE SAVE_A3S
 MODULE PROCEDURE SAVE_A3VS
END INTERFACE

!!### PUBLIC ACCESS LIST
PUBLIC :: SAVE


!!## MODULE PROCEDURES
CONTAINS


!!### Rank 1 Array SAVEing Procedures
SUBROUTINE SAVE_A1Rsp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rsp
INCLUDE "06-B-SUB_SAVE_A1R.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1Rdp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rdp
INCLUDE "06-B-SUB_SAVE_A1R.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVE_A1Csp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Csp
INCLUDE "06-B-SUB_SAVE_A1C.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1Cdp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Cdp
INCLUDE "06-B-SUB_SAVE_A1C.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE




SUBROUTINE SAVE_A1I1(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I1
INCLUDE "06-B-SUB_SAVE_A1I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1I2(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I2
INCLUDE "06-B-SUB_SAVE_A1I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1I4(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I4
INCLUDE "06-B-SUB_SAVE_A1I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1I8(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I8
INCLUDE "06-B-SUB_SAVE_A1I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVE_A1L1(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L1
INCLUDE "06-B-SUB_SAVE_A1L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1L2(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L2
INCLUDE "06-B-SUB_SAVE_A1L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1L4(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L4
INCLUDE "06-B-SUB_SAVE_A1L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1S(SA,A)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVE_A1S.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A1VS(SA,A)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVE_A1VS.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A1VS.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE





!!### Rank 2 Array SAVEing Procedures
SUBROUTINE SAVE_A2Rsp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rsp
INCLUDE "06-B-SUB_SAVE_A2R.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2Rdp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rdp
INCLUDE "06-B-SUB_SAVE_A2R.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVE_A2Csp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Csp
INCLUDE "06-B-SUB_SAVE_A2C.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2Cdp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Cdp
INCLUDE "06-B-SUB_SAVE_A2C.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE




SUBROUTINE SAVE_A2I1(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I1
INCLUDE "06-B-SUB_SAVE_A2I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2I2(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I2
INCLUDE "06-B-SUB_SAVE_A2I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2I4(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I4
INCLUDE "06-B-SUB_SAVE_A2I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2I8(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I8
INCLUDE "06-B-SUB_SAVE_A2I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVE_A2L1(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L1
INCLUDE "06-B-SUB_SAVE_A2L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2L2(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L2
INCLUDE "06-B-SUB_SAVE_A2L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2L4(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L4
INCLUDE "06-B-SUB_SAVE_A2L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2S(SA,A)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVE_A2S.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A2VS(SA,A)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVE_A2VS.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A2VS.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE






!!### Rank 3 Array SAVEing Procedures
SUBROUTINE SAVE_A3Rsp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rsp
INCLUDE "06-B-SUB_SAVE_A3R.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3Rdp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_R = KIND_Rdp
INCLUDE "06-B-SUB_SAVE_A3R.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVE_A3Csp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Csp
INCLUDE "06-B-SUB_SAVE_A3C.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3Cdp(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_C = KIND_Cdp
INCLUDE "06-B-SUB_SAVE_A3C.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE




SUBROUTINE SAVE_A3I1(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I1
INCLUDE "06-B-SUB_SAVE_A3I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3I2(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I2
INCLUDE "06-B-SUB_SAVE_A3I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3I4(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I4
INCLUDE "06-B-SUB_SAVE_A3I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3I8(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_I = KIND_I8
INCLUDE "06-B-SUB_SAVE_A3I.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE


SUBROUTINE SAVE_A3L1(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L1
INCLUDE "06-B-SUB_SAVE_A3L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3L2(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L2
INCLUDE "06-B-SUB_SAVE_A3L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3L4(SA,A)
!!#### PARAMETERS
INTEGER     ,PARAMETER :: KIND_L = KIND_L4
INCLUDE "06-B-SUB_SAVE_A3L.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3S(SA,A)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVE_A3S.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE

SUBROUTINE SAVE_A3VS(SA,A)
!!#### PARAMETERS
INCLUDE "06-B-SUB_SAVE_A3VS.f90.hdr"
INCLUDE "06-B-SUB_SAVE.f90.hdr"
!!--begin--
INCLUDE "06-B-SUB_SAVE.f90.sup"
INCLUDE "06-B-SUB_SAVE_A3VS.f90.bdy"
INCLUDE "06-B-SUB_SAVE.f90.wup"
!!--end--
END SUBROUTINE



END MODULE
