MODULE FUN_xyQUADRILATERAL
!!#### PURPOSE
!! Determine the QUADRILATERAL connecting the points in the list.

!!#### EXTERNAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_Rsp,KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))

!!#### EXTERNAL PARAMETERS
USE PAR_ComputationalGeometry                  !!((02-A-PAR_ComputationalGeometry.f90))

!!#### EXTERNAL PROCEDURES
USE FUN_xyCONVEXHULL                           !!((07-B-FUN_xyCONVEXHULL.f90))
USE FUN_xyCOLINEAR                             !!((05-B-FUN_xyCOLINEAR.f90))
USE FUN_xyCONTIGUOUS                           !!((06-B-FUN_xyCONTIGUOUS.f90))

!!#### DEFAULT IMPLICIT
IMPLICIT NONE

!!#### DEFAULT ACCESS
PRIVATE

!!#### PROCEDURE OVERLOADING
INTERFACE xyQUADRILATERAL_Lsx
 MODULE PROCEDURE xyQUADRILATERAL_Lsx_Rsp
 MODULE PROCEDURE xyQUADRILATERAL_Lsx_Rdp
END INTERFACE

INTERFACE xyQUADRILATERAL_P4
 MODULE PROCEDURE xyQUADRILATERAL_P4_Rsp
 MODULE PROCEDURE xyQUADRILATERAL_P4_Rdp
END INTERFACE

!!#### PUBLIC ACCESS LIST
PUBLIC :: xyQUADRILATERAL_Lsx
PUBLIC :: xyQUADRILATERAL_P4

CONTAINS


PURE FUNCTION xyQUADRILATERAL_Lsx_Rsp( N , Lsx ) RESULT(xyQg)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp  !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "08-A-FUN_xyQUADRILATERAL_Lsx.f90.hdr"
!!--begin--
INCLUDE "08-A-FUN_xyQUADRILATERAL_Lsx.f90.bdy"
!!--end--
END FUNCTION


PURE FUNCTION xyQUADRILATERAL_Lsx_Rdp( N , Lsx ) RESULT(xyQg)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp  !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "08-A-FUN_xyQUADRILATERAL_Lsx.f90.hdr"
!!--begin--
INCLUDE "08-A-FUN_xyQUADRILATERAL_Lsx.f90.bdy"
!!--end--
END FUNCTION



PURE FUNCTION xyQUADRILATERAL_P4_Rsp( P4 ) RESULT(xyQg)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp  !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "08-A-FUN_xyQUADRILATERAL_P4.f90.hdr"
!!--begin--
INCLUDE "08-A-FUN_xyQUADRILATERAL_P4.f90.bdy"
!!--end--
END FUNCTION


PURE FUNCTION xyQUADRILATERAL_P4_Rdp( P4 ) RESULT(xyQg)
!!#### LOCAL KINDS
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp  !!((01-A-KND_IntrinsicTypes.f90))
INCLUDE "08-A-FUN_xyQUADRILATERAL_P4.f90.hdr"
!!--begin--
INCLUDE "08-A-FUN_xyQUADRILATERAL_P4.f90.bdy"
!!--end--
END FUNCTION


END MODULE
