!!# TOOLBOX MODULE <<TBX_SIO>>
MODULE TBX_SIO

!!## PURPOSE
!! Provide users with a simple yet powerful Serial Input/Output
!! toolbox.

!!## AUTHOR
!! William A. Wieselquist | william.wieselquist@gmail.com


!!## EXTERNAL KINDS
USE KND_IntrinsicTypes                        !!((01-A-KND_IntrinsicTypes.f90))


!!## FORTRAN STANDARDS MODULES
USE ISO_varying_string                        !!((03-A-ISO_varying_string.f90))


!!## EXTERNAL PARAMETERS
USE PAR_IntrinsicLengths                      !!((02-A-PAR_IntrinsicLengths.f90))

!!## GLOBAL USER MODULES
USE USR_SIO                                   !!((09-A-USR_SIO.f90))
USE USR_fdbk                                  !!((08-C-USR_fdbk.f90))

!!## GLOBAL ASSIGNMENTS
USE ASN_IntrinsicS                            !!((05-B-ASN_IntrinsicS.f90))

!!## GLOBAL BINARY OPERATORS
USE BOP_sEQ                                   !!((03-A-BOP_sEQ.f90))

!!## EXTERNAL PROCEDURES
USE FUN_STR                                   !!((05-B-FUN_STR.f90))
USE FUN_Error                                 !!((04-A-FUN_Error.f90))
USE FUN_INDEXa                                !!((08-B-FUN_INDEXa.f90))
USE SUB_Reallocate                            !!((04-B-SUB_Reallocate.f90))
USE SUB_CLEAR                                 !!((04-A-SUB_CLEAR.f90))
USE FUN_VSTR                                  !!((05-B-FUN_VSTR.f90))

!!## GLOBAL LIBRARIES
USE LIB_GenericPhrases                        !!((07-B-LIB_GenericPhrases.f90))

!!## DEFAULT IMPLICIT
IMPLICIT NONE

!!## DEFAULT ACCESS
PRIVATE

!!## INTERFACES
!!### PROCEDURE OVERLOADING: DATABLOCK
INTERFACE DATABLOCK
 MODULE PROCEDURE DATABLOCK_P2S
 MODULE PROCEDURE DATABLOCK_P2VS
 MODULE PROCEDURE DATABLOCK_P2I1
 MODULE PROCEDURE DATABLOCK_P2I2
 MODULE PROCEDURE DATABLOCK_P2I4
 MODULE PROCEDURE DATABLOCK_P2I8
 MODULE PROCEDURE DATABLOCK_P2Csp
 MODULE PROCEDURE DATABLOCK_P2Cdp
 MODULE PROCEDURE DATABLOCK_P2Rsp
 MODULE PROCEDURE DATABLOCK_P2Rdp
 MODULE PROCEDURE DATABLOCK_P2L1
 MODULE PROCEDURE DATABLOCK_P2L2
 MODULE PROCEDURE DATABLOCK_P2L4
 MODULE PROCEDURE DATABLOCK_P1S
 MODULE PROCEDURE DATABLOCK_P1VS
 MODULE PROCEDURE DATABLOCK_P1I1
 MODULE PROCEDURE DATABLOCK_P1I2
 MODULE PROCEDURE DATABLOCK_P1I4
 MODULE PROCEDURE DATABLOCK_P1I8
 MODULE PROCEDURE DATABLOCK_P1Csp
 MODULE PROCEDURE DATABLOCK_P1Cdp
 MODULE PROCEDURE DATABLOCK_P1Rsp
 MODULE PROCEDURE DATABLOCK_P1Rdp
 MODULE PROCEDURE DATABLOCK_P1L1
 MODULE PROCEDURE DATABLOCK_P1L2
 MODULE PROCEDURE DATABLOCK_P1L4
 MODULE PROCEDURE DATABLOCK_A2S
 MODULE PROCEDURE DATABLOCK_A2VS
 MODULE PROCEDURE DATABLOCK_A2I1
 MODULE PROCEDURE DATABLOCK_A2I2
 MODULE PROCEDURE DATABLOCK_A2I4
 MODULE PROCEDURE DATABLOCK_A2I8
 MODULE PROCEDURE DATABLOCK_A2Csp
 MODULE PROCEDURE DATABLOCK_A2Cdp
 MODULE PROCEDURE DATABLOCK_A2Rsp
 MODULE PROCEDURE DATABLOCK_A2Rdp
 MODULE PROCEDURE DATABLOCK_A2L1
 MODULE PROCEDURE DATABLOCK_A2L2
 MODULE PROCEDURE DATABLOCK_A2L4
 MODULE PROCEDURE DATABLOCK_A1VS
 MODULE PROCEDURE DATABLOCK_A1S
 MODULE PROCEDURE DATABLOCK_A1I1
 MODULE PROCEDURE DATABLOCK_A1I2
 MODULE PROCEDURE DATABLOCK_A1I4
 MODULE PROCEDURE DATABLOCK_A1I8
 MODULE PROCEDURE DATABLOCK_A1Csp
 MODULE PROCEDURE DATABLOCK_A1Cdp
 MODULE PROCEDURE DATABLOCK_A1Rsp
 MODULE PROCEDURE DATABLOCK_A1Rdp
 MODULE PROCEDURE DATABLOCK_A1L1
 MODULE PROCEDURE DATABLOCK_A1L2
 MODULE PROCEDURE DATABLOCK_A1L4
ENDINTERFACE

!!##$ PROCEDURE OVERLOADING: READ_DATABLOCK
INTERFACE READ_DATABLOCK
 MODULE PROCEDURE READ_DATABLOCK_A2S
 MODULE PROCEDURE READ_DATABLOCK_A2VS
 MODULE PROCEDURE READ_DATABLOCK_A2I1
 MODULE PROCEDURE READ_DATABLOCK_A2I2
 MODULE PROCEDURE READ_DATABLOCK_A2I4
 MODULE PROCEDURE READ_DATABLOCK_A2I8
 MODULE PROCEDURE READ_DATABLOCK_A2Csp
 MODULE PROCEDURE READ_DATABLOCK_A2Cdp
 MODULE PROCEDURE READ_DATABLOCK_A2Rsp
 MODULE PROCEDURE READ_DATABLOCK_A2Rdp
 MODULE PROCEDURE READ_DATABLOCK_A2L1
 MODULE PROCEDURE READ_DATABLOCK_A2L2
 MODULE PROCEDURE READ_DATABLOCK_A2L4
 MODULE PROCEDURE READ_DATABLOCK_A1S
 MODULE PROCEDURE READ_DATABLOCK_A1VS
 MODULE PROCEDURE READ_DATABLOCK_A1I1
 MODULE PROCEDURE READ_DATABLOCK_A1I2
 MODULE PROCEDURE READ_DATABLOCK_A1I4
 MODULE PROCEDURE READ_DATABLOCK_A1I8
 MODULE PROCEDURE READ_DATABLOCK_A1Csp
 MODULE PROCEDURE READ_DATABLOCK_A1Cdp
 MODULE PROCEDURE READ_DATABLOCK_A1Rsp
 MODULE PROCEDURE READ_DATABLOCK_A1Rdp
 MODULE PROCEDURE READ_DATABLOCK_A1L1
 MODULE PROCEDURE READ_DATABLOCK_A1L2
 MODULE PROCEDURE READ_DATABLOCK_A1L4
ENDINTERFACE

!!### PROCEDURE OVERLOADING: WRITE_DATABLOCK
INTERFACE WRITE_DATABLOCK
 MODULE PROCEDURE WRITE_DATABLOCK_A2S
 MODULE PROCEDURE WRITE_DATABLOCK_A2VS
 MODULE PROCEDURE WRITE_DATABLOCK_A2I1
 MODULE PROCEDURE WRITE_DATABLOCK_A2I2
 MODULE PROCEDURE WRITE_DATABLOCK_A2I4
 MODULE PROCEDURE WRITE_DATABLOCK_A2I8
 MODULE PROCEDURE WRITE_DATABLOCK_A2Csp
 MODULE PROCEDURE WRITE_DATABLOCK_A2Cdp
 MODULE PROCEDURE WRITE_DATABLOCK_A2Rsp
 MODULE PROCEDURE WRITE_DATABLOCK_A2Rdp
 MODULE PROCEDURE WRITE_DATABLOCK_A2L1
 MODULE PROCEDURE WRITE_DATABLOCK_A2L2
 MODULE PROCEDURE WRITE_DATABLOCK_A2L4
 MODULE PROCEDURE WRITE_DATABLOCK_A1S
 MODULE PROCEDURE WRITE_DATABLOCK_A1VS
 MODULE PROCEDURE WRITE_DATABLOCK_A1I1
 MODULE PROCEDURE WRITE_DATABLOCK_A1I2
 MODULE PROCEDURE WRITE_DATABLOCK_A1I4
 MODULE PROCEDURE WRITE_DATABLOCK_A1I8
 MODULE PROCEDURE WRITE_DATABLOCK_A1Csp
 MODULE PROCEDURE WRITE_DATABLOCK_A1Cdp
 MODULE PROCEDURE WRITE_DATABLOCK_A1Rsp
 MODULE PROCEDURE WRITE_DATABLOCK_A1Rdp
 MODULE PROCEDURE WRITE_DATABLOCK_A1L1
 MODULE PROCEDURE WRITE_DATABLOCK_A1L2
 MODULE PROCEDURE WRITE_DATABLOCK_A1L4
END INTERFACE

!!### MISCELLANEOUS
INTERFACE COMMAND_NOT_RECOGNIZED
 MODULE PROCEDURE COMMAND_NOT_RECOGNIZED_
END INTERFACE

!!## IDENTIFICATION
CHARACTER(*),PARAMETER :: mod_ ="TBX_SIO"
CHARACTER(*),PARAMETER :: file_="10-A-TBX_SIO.f90"

!!## PUBLIC ACCESS LIST
PUBLIC :: TYPE_SIO
PUBLIC :: CONNECT
!! * read/write a command
PUBLIC :: READ_COMMAND
PUBLIC :: WRITE_COMMAND
!! * read/write arguments
PUBLIC :: BEGIN_ARGUMENTS
PUBLIC :: ARGUMENT
PUBLIC :: END_ARGUMENTS
!! * read/write datablocks
PUBLIC :: DATABLOCK
PUBLIC :: READ_DATABLOCK
PUBLIC :: WRITE_DATABLOCK
!! * disconnect
PUBLIC :: DISCONNECT
!! * simple inquiry
PUBLIC :: Reading
PUBLIC :: Writing
PUBLIC :: Formatted
PUBLIC :: Unformatted
PUBLIC :: Stopped
PUBLIC :: getNextLine,putStopper,putEndofLine
!! * other procedures
PUBLIC :: FMT
PUBLIC :: READ_ARGUMENT
PUBLIC :: WRITE_ARGUMENT
PUBLIC :: PARSE_COMMAND
PUBLIC :: WRITE_CHARS
PUBLIC :: READ_CHARS
PUBLIC :: INQUIRE_ACTION
PUBLIC :: INQUIRE_ACCESS
PUBLIC :: INQUIRE_BLANK
PUBLIC :: INQUIRE_DELIM
PUBLIC :: INQUIRE_EXIST
PUBLIC :: INQUIRE_FORM
PUBLIC :: INQUIRE_PAD
PUBLIC :: INQUIRE_POSITION
PUBLIC :: INQUIRE_RECL
PUBLIC :: LEN_FMT
!! * error/warning/comment statements
PUBLIC :: COMMAND_NOT_RECOGNIZED

CONTAINS


PURE FUNCTION COMMAND_NOT_RECOGNIZED_( sio , mod , proc , addspec ) RESULT(Phrase)
!!#### PURPOSE
!! Prints a "command-not-recognized statement".

!!#### REQUIRED INPUT
TYPE(TYPE_SIO)              ,INTENT(IN) :: sio
CHARACTER(LEN=*,KIND=KIND_S),INTENT(IN) :: mod,proc,addspec

!!#### REQUIRED OUTPUT
!! * phrase to output
TYPE(varying_string) :: Phrase

!!--begin--
!! Assemble the phrase.
Phrase = MODPROC(mod,proc)//&
         "the "// TRIM(addspec) // "command: " //sio%cmdbeg//TRIM(STR(sio%cmd))//&
         " on line="//TRIM(STR(sio%LINE_NUM))//&
         " of file="//TRIM(STR(sio%FILE))//&
         " was not recognized."

!!--end--
ENDFUNCTION

!!**begin DATABLOCK_P1
SUBROUTINE DATABLOCK_P1Rsp(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1Rsp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1Rdp(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1Rdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1Csp(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1Csp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1Cdp(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1Cdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1I1(SIO,N1,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1I1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1I2(SIO,N1,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1I2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1I4(SIO,N1,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1I4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1I8(SIO,N1,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1I8"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1L1(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1L1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1L.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1L2(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1L2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1L.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1L4(SIO,N1,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1L4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1L.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1S(SIO,N1,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1S"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P1VS(SIO,N1,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P1VS"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P1.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end DATABLOCK_P1



!!**begin DATABLOCK_P2
SUBROUTINE DATABLOCK_P2Rsp(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2Rsp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2Rdp(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2Rdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2Csp(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2Csp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2Cdp(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2Cdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2I1(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2I1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2I2(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2I2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2I4(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2I4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2I8(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2I8"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2L1(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2L1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2L.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2L2(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2L2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2L.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2L4(SIO,N1,N2,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2L4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2L.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2S(SIO,N1,N2,X,FdBk,Indent)
INTEGER,PARAMETER :: KIND_S=KIND_Sen
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2S"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_P2VS(SIO,N1,N2,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_P2VS"
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_P2.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end DATABLOCK_P2




!!**begin DATABLOCK_A1
SUBROUTINE DATABLOCK_A1Rsp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1Rsp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1Rdp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1Rdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1Csp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1Csp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1Cdp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1Cdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1I1(SIO,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1I1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1I2(SIO,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1I2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1I4(SIO,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1I4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1I8(SIO,X,FdBk,Keys,Indent,CaseSen)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1I8"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1I.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1L1(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1L1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1L2(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1L2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1L4(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1L4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1S(SIO,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1S"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A1VS(SIO,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A1VS"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A1.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end DATABLOCK_A1




!!**begin DATABLOCK_A2
SUBROUTINE DATABLOCK_A2Rsp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2Rsp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2Rdp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2Rdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2R.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2Csp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2Csp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2Cdp(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2Cdp"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2C.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2I1(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2I1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2I2(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2I2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2I4(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2I4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2I8(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2I8"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2I.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2L1(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2L1"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2L2(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2L2"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2L4(SIO,X,FdBk,Indent)
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2L4"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2L.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2S(SIO,X,FdBk,Indent)
INTEGER,PARAMETER :: KIND_S=KIND_Sen
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2S"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE DATABLOCK_A2VS(SIO,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "DATABLOCK_A2VS"
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__DATABLOCK_A2.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end DATABLOCK_A2


!!**begin READ_DATABLOCK_A2 routines
SUBROUTINE READ_DATABLOCK_A2I1(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2I1"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I1
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2I2(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2I2"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I2
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2I4(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2I4"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I4
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2I8(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2I8"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I8
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2Rsp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2Rsp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2R.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2Rdp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2Rdp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2R.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2Csp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2Csp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2C.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2Cdp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2Cdp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2C.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2L1(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2L1"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2L2(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2L2"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2L4(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A2L4"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2S(SIO,X,FdBk)
INTEGER,PARAMETER :: KIND_S=KIND_Sen
CHARACTER(*),PARAMETER :: proc_ = "READ_DATABLOCK_A2S"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2S.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A2VS(SIO,X,FdBk)
CHARACTER(*),PARAMETER :: proc_ = "READ_DATABLOCK_A2VS"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A2VS.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end READ_DATABLOCK_A2



!!**begin READ_DATABLOCK_A1
SUBROUTINE READ_DATABLOCK_A1I1(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1I1"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I1
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1I2(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1I2"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I2
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1I4(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1I4"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I4
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1I8(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1I8"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I8
 INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1Rsp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1Rsp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1R.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1Rdp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1Rdp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1R.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1Csp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1Csp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1C.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1Cdp(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1Cdp"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1C.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1L1(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1L1"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1L2(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1L2"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1L4(SIO,X,FdBk)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="READ_DATABLOCK_A1L4"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1S(SIO,X,FdBk)
INTEGER,PARAMETER :: KIND_S=KIND_Sen
CHARACTER(*),PARAMETER :: proc_ = "READ_DATABLOCK_A1S"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1S.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE READ_DATABLOCK_A1VS(SIO,X,FdBk)
CHARACTER(*),PARAMETER :: proc_ = "READ_DATABLOCK_A1VS"
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__READ_DATABLOCK_A1VS.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end READ_DATABLOCK_A1 routines



!!**begin WRITE_DATABLOCK_A2 routines
SUBROUTINE WRITE_DATABLOCK_A2I1(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2I1"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I1
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE


SUBROUTINE WRITE_DATABLOCK_A2I2(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2I2"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I2
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2I4(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2I4"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I4
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2I8(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2I8"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2I.f90.hdr"
!!
FMT_ => SIO%FMT_I8
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2Rsp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2Rsp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2R.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2Rdp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2Rdp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2R.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2Csp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2Csp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2C.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2Cdp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2Cdp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2C.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2L1(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2L1"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2L2(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2L2"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2L4(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A2L4"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2S(SIO,X,FdBk,Indent)
INTEGER,PARAMETER :: KIND_S=KIND_Sen
CHARACTER(*),PARAMETER :: proc_ = "WRITE_DATABLOCK_A2S"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2S.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A2VS(SIO,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "WRITE_DATABLOCK_A2VS"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A2VS.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end WRITE_DATABLOCK_A2



!!**begin WRITE_DATABLOCK_A1
SUBROUTINE WRITE_DATABLOCK_A1I1(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1I1"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I1
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1I2(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1I2"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I2
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1I4(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1I4"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I4
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1I8(SIO,X,FdBk,Keys,Indent,CaseSen)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_I=>KIND_I8  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1I8"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I.f90.hdr"
!!
IF( PRESENT(Keys) )THEN
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1I_KEYS.f90.bdy"
ELSE
 FMT_ => SIO%FMT_I8
 INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
 FMT_ => NULL()
ENDIF
!!
ENDSUBROUTINE


SUBROUTINE WRITE_DATABLOCK_A1Rsp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rsp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1Rsp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1R.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1Rdp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_R=>KIND_Rdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1Rdp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1R.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1Csp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Csp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1Csp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1C.f90.hdr"
!!
FMT_ => SIO%FMT_sp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1Cdp(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_C=>KIND_Cdp !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1Cdp"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1C.f90.hdr"
!!
FMT_ => SIO%FMT_dp
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1L1(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L1  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1L1"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1L2(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L2  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1L2"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1L4(SIO,X,FdBk,Indent)
!!PURPOSE
USE KND_IntrinsicTypes,ONLY: KIND_L=>KIND_L4  !!((01-A-KND_IntrinsicTypes.f90))
CHARACTER(*),PARAMETER :: proc_="WRITE_DATABLOCK_A1L4"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1L.f90.hdr"
!!
FMT_ => SIO%FMT_L
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK.f90.bdy"
FMT_ => NULL()
!!
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1S(SIO,X,FdBk,Indent)
INTEGER,PARAMETER :: KIND_S=KIND_Sen
CHARACTER(*),PARAMETER :: proc_ = "WRITE_DATABLOCK_A1S"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1S.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1S.f90.bdy"
!!--end--
ENDSUBROUTINE

SUBROUTINE WRITE_DATABLOCK_A1VS(SIO,X,FdBk,Indent)
CHARACTER(*),PARAMETER :: proc_ = "WRITE_DATABLOCK_A1VS"
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1VS.f90.hdr"
!!--begin--
INCLUDE "10-A-TBX_SIO__WRITE_DATABLOCK_A1VS.f90.bdy"
!!--end--
ENDSUBROUTINE
!!**end WRITE_DATABLOCK_A1 routines

ENDMODULE
